### PR TITLE
Fix counter path from `init`

### LINKED ISSUE #1647: Counter path on init is incorrect
When you run `init` it is missing the `cadence/` from the path.

### PR DESCRIPTION
**Pull request by chasefleming**
Closes #1647 

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: internal/super/generate.go [hunk 1]
```diff
@@ -338,6 +338,8 @@ func (g *Generator) generate(templateType, templateName, name, account string, d
 	filenameWithBasePath := filepath.Join(rootDir, basePath, account, filename)
 	relativeFilenameWithBasePath := filepath.Join(basePath, account, filename)
 
+	fmt.Println("relativeFilenameWithBasePath: ", relativeFilenameWithBasePath)
```
Comment (jribbink) [inline internal/super/generate.go:341]: remove

**Review by jribbink — APPROVED** [review]

**Review by ianthpun — APPROVED** [review]
