### PR TITLE
Fix nested paths in `flow cadence lint`

### LINKED ISSUE #2214: `flow cadence lint` does not resolve nested String imports correctly

### PR DESCRIPTION
**Pull request by jribbink**
Closes #2214 

## Description

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: internal/cadence/linter.go [hunk 1]
```diff
@@ -237,6 +244,37 @@ func (l *linter) handleImport(
...
+// isPathLocation returns true if the location is a file path (contains .cdc)
+func (l *linter) isPathLocation(location common.Location) bool {
+	stringLocation, ok := location.(common.StringLocation)
+	if !ok {
+		return false
+	}
+	return strings.Contains(stringLocation.String(), ".cdc")
+}
+
+// normalizePathLocation normalizes a relative path import against a base location
```
Comment (chasefleming) [inline internal/cadence/linter.go]: same

**Review by chasefleming — APPROVED** [review]
