### PR TITLE
QA Check account and contract exists

### LINKED ISSUE #194: flow project deploy with wrong account
### Problem

flow.json has an account under deployments/emulator that is not present in the flow.json file for that network

flow project deploy -n emulator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4a24b5a]

goroutine 1 [running]:
github.com/onflow/flow-cli/pkg/flowcli/project.(*Project).ContractsByNetwork(0xc00014c3f0, 0x7ffeefbff9e7, 0x8, 0xc000387af0, 0x40105e8, 0x4fb7f80)
	github.com/onflow/flow-cli/pkg/flowcli/project/project.go:187 +0x31a
github.com/onflow/flow-cli/pkg/flowcli/project.(*Project).ContractConflictExists(0xc00014c3f0, 0x7ffeefbff9e7, 0x8, 0x15)
	github.com/onflow/flow-cli/pkg/flowcli/project/project.go:133 +0x45
github.com/onflow/flow-cli/pkg/flowcli/services.(*Project).Deploy(0xc00014cc30, 0x7ffeefbff9e7, 0x8, 0xc000617c00, 0xc00014cba0, 0xc00014cbd0, 0xc00014ccc0, 0xc00014cc00, 0xc00014cb10)
	github.com/onflow/flow-cli/pkg/flowcli/services/project.go:104 +0x6c
github.com/onflow/flow-cli/internal/project.glob..func1(0x5c3d7c0, 0xc000138fe0, 0x0, 0x2, 0x0, 0x0, 0x50042c5, 0x4, 0x0, 0x0, ...)
	github.com/onflow/flow-cli/internal/project/deploy.go:47 +0x5b
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x5c3d7c0, 0xc000138fe0, 0x0, 0x2)
	github.com/onflow/flow-cli/internal/command/command.go:170 +0x2dd
github.com/spf13/cobra.(*Command).execute(0x5c3d7c0, 0xc00003c080, 0x2, 0x2, 0x5c3d7c0, 0xc00003c080)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c7340, 0xc000387f70, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/onflow/flow-cli/cmd/flow/main.go:65 +0x365

### PR DESCRIPTION
**Pull request by sideninja**
Closes #194 

## Description
Explicitly check that account and contracts exists on deployments. If the user inputted the wrong account name in the configuration it could crash CLI with null pointer exception.

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: pkg/flowcli/project/project.go [hunk 1]
```diff
@@ -131,7 +131,10 @@ func newProject(conf *config.Config, composer *config.Loader) (*Project, error)
 // The CLI currently does not allow the same contract to be deployed to multiple
 // accounts in the same network.
 func (p *Project) ContractConflictExists(network string) bool {
-	contracts := p.ContractsByNetwork(network)
+	contracts, error := p.ContractsByNetwork(network)
+	if error != nil {
```
Comment (psiemens) [inline pkg/flowcli/project/project.go:135]:
```suggestion
	contracts, err := p.ContractsByNetwork(network)
	if err != nil {
```

**Review by psiemens — APPROVED** [review]
Nice improvement 👍
