### PR TITLE
Fix version check

### LINKED ISSUE #1626: Version check doesn't work
Version check seems to warn about new version even though I have the latest version. 

image

### PR DESCRIPTION
**Pull request by jribbink**
Closes #1626 

## Description

Fixes regression in version checking

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by ianthpun — APPROVED** [review]

File: internal/command/command.go [hunk 1]
```diff
@@ -287,19 +287,21 @@ func checkVersion(logger output.Logger) {
 		return
 	}
 
-	latestVersion, ok := versions["stable"].(string)
+	latestVersionRaw, ok := versions["stable"].(string)
 	if !ok {
 		return
 	}
 
+	latestVersion := fmt.Sprintf("v%s", latestVersionRaw)
```
Comment (chasefleming) [inline internal/command/command.go:295]: What if the "v" already exists on it?

Comment (jribbink) [reply internal/command/command.go:295]: It doesn't in the current homebrew API spec today, but yeah, probably doesn't hurt to check
