### PR TITLE
Add show diff flag to update-contract command and fix regression

### LINKED ISSUE #962: Show contract update diff on update command
The contract update diff should also be accessible on the `flow accounts update-contract` command.

### PR DESCRIPTION
**Pull request by chasefleming**
Closes #962, #1000 

## Description

- Fixes regression after 1.0.0 that broke showing diff on `flow project deploy` (logger runs while waiting for user input)
- Adds `--show-diff` options to `flow accounts update-contract`
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: flowkit/flowkit.go [hunk 1]
```diff
@@ -307,8 +307,6 @@ func (f *Flowkit) AddContract(
 		return flow.EmptyID, false, err
 	}
 
-	f.logger.StartProgress(fmt.Sprintf("Checking contract '%s' on account '%s'...", name, account.Address))
```
Comment (sideninja) [inline flowkit/flowkit.go:310]: I don't like this being removed, it provides valuable progress to the user while the update is happening.

Comment (sideninja) [reply flowkit/flowkit.go:310]: What I believe it should be done is for the diff prompt to use the same logger, we should never use fmt.Println to output data, just because of this kind of issues. So make sure to use the logger here https://github.com/onflow/flow-cli/blob/master/internal/util/prompt.go#L257 instead of fmt.Println. That way the logger will hide the progress log.

Comment (chasefleming) [reply flowkit/flowkit.go]: Changed

File: internal/util/prompt.go [hunk 2]
```diff
@@ -250,23 +250,25 @@ func addAnotherContractToDeploymentPrompt() bool {
 // ShowContractDiffPrompt shows a diff between the new contract and the existing contract
 // and asks the user if they wish to continue with the deployment
 // returns true if the user wishes to continue with the deployment and false otherwise
-func ShowContractDiffPrompt(newContract []byte, existingContract []byte) bool {
-	dmp := diffmatchpatch.New()
-	diffs := dmp.DiffMain(string(newContract), string(existingContract), false)
-	diffString := dmp.DiffPrettyText(diffs)
-	fmt.Println(diffString)
+func ShowContractDiffPrompt(logger *output.Logger) func([]byte, []byte) bool {
```
Comment (nvdtf) [inline internal/util/prompt.go:253]: `output.Logger` is an interface so we can drop the pointer, This will result in a simpler syntax.

**Review by nvdtf — APPROVED** [review]
✨

**Review by DylanTinianov — APPROVED** [review]
Look good!
