### PR TITLE
Bugfix ENV parsing

### LINKED ISSUE #947: regression in 0.47.0 with flow.json parsing?
flow deploy -n mainnet --update
❌ Config Error: encoding/hex: invalid byte: U+0024 '$'

works in older versions. 

Git repo this is in is private unfortunately. but it has env vars in flow json.

### PR DESCRIPTION
**Pull request by sideninja**
Closes #947 

## Description
Expand environment parsing to support previously supported `${}` format.
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by DylanTinianov — APPROVED** [review]

File: pkg/flowkit/config/json/account.go [hunk 1]
```diff
@@ -94,11 +94,23 @@ func transformSimpleToConfig(accountName string, a simpleAccount) (*config.Accou
 // tryReplaceEnv checks if value matches env regex, if it does it check whether the value was set in env,
 // if not set then it errors, otherwise it replaces the value with set env variable, and also returns the original key.
 func tryReplaceEnv(value string) (replaced string, original string, err error) {
-	if envPresent, _ := regexp.MatchString("^\\$\\w+", value); !envPresent {
+	envRegex, err := regexp.Compile(`^\$[{]?(\w+)[}]?`)
```
Comment (bluesign) [inline pkg/flowkit/config/json/account.go:97]: maybe `^\$((\w+)|\{(\w+)\})` to prevent partial match

Comment (sideninja) [reply pkg/flowkit/config/json/account.go:97]: good catch
