### PR TITLE
Windows path fix

### LINKED ISSUE #1183: `flow project deploy` broken on windows
When I deploy my contracts in flow.json on linux/mac, it works totally fine. But windows seems to be broken.

image
Something to do with not reading the imports in contracts correctly. Maybe due to wrongful file paths

### PR DESCRIPTION
**Pull request by jribbink**
Closes #1183 

## Description

This fixes bugs related to Windows path formatting.  We were using the [`"path"`](https://pkg.go.dev/path) package in a few places that should have been using[ `"path/filepath"`](https://pkg.go.dev/path/filepath).

Some issues with this were more theoretical and didn't seem to surface yet (absolute paths like `C:/foo/bar` would not be recognized as absolute).  But most critically the mixing of `"path"` and `"path/filepath"` meant that when doing comparisons/dictionary lookups to see if paths were equivalent the different format would result in two paths not matching (this is what broke deployment).

The PR also ensures that all paths written to `flow.json` are in UNIX format for cross-platform compatibility.  This is the pattern adopted by NPM in the `package.json` file.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -24,17 +35,20 @@ binary: $(BINARY)
 
 .PHONY: install-tools
 install-tools:
-	cd ${GOPATH}; \
```
Comment (sideninja) [inline Makefile:27]: can we please extract this as a separate PR

File: flowkit/state_test.go [hunk 2]
```diff
@@ -343,7 +344,7 @@ func generateAliasesComplexProject() State {
```
Comment (sideninja) [inline flowkit/state_test.go:344]: could we add some windows style paths to test

File: internal/super/files_test.go [hunk 3]
```diff
@@ -20,19 +20,19 @@ package super
...
 )
 
 func Test_AccountFromPath(t *testing.T) {
 	paths := [][]string{ // first is path, second is account name
-		{"cadence/contracts/alice/foo.cdc", "alice"},
-		{"cadence/contracts/alice", "alice"},
-		{"cadence/contracts/alice/boo/foo.cdc", ""},
-		{"cadence/contracts/foo.cdc", ""},
-		{"cadence/contracts/foo/bar/goo/foo", ""},
+		{filepath.FromSlash("cadence/contracts/alice/foo.cdc"), "alice"},
```
Comment (sideninja) [inline internal/super/files_test.go:31]: you can just call this function inside the for loop once

**Review by chasefleming — APPROVED** [review]
