### PR TITLE
Fix embedded flags issue when running Dependency Manager flags manually

### LINKED ISSUE #1519: Embedded flags work in tests but not manually

### PR DESCRIPTION
**Pull request by chasefleming**
Closes #1519 

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: internal/dependencymanager/dependencyinstaller.go [hunk 1]
```diff
@@ -74,6 +76,11 @@ type dependencyManagerFlagsCollection struct {
 	skipAlias       bool `default:"false" flag:"skip-alias" info:"Skip prompting for an alias"`
```
Comment (jribbink) [inline internal/dependencymanager/dependencyinstaller.go:76]: If we're not using the sconfig metadata, we should probably just remove it.  Otherwise this could be misleading for someone looking at the code later

File: internal/dependencymanager/dependencyinstaller.go [hunk 2]
```diff
@@ -74,6 +76,11 @@ type dependencyManagerFlagsCollection struct {
...
 }
 
+func (f *dependencyManagerFlagsCollection) AddToCommand(cmd *cobra.Command) {
+	cmd.Flags().BoolVar(&f.skipDeployments, "skip-deployments", false, "Skip adding the dependency to deployments")
+	cmd.Flags().BoolVar(&f.skipAlias, "skip-alias", false, "Skip prompting for an alias")
```
Comment (jribbink) [inline internal/dependencymanager/dependencyinstaller.go:81]: Option no. 2 is to continue using sconfig to bind the flags & then the syntax could remain unchanged

```suggestion
err := sconfig.New(f).
	FromEnvironment(util.EnvPrefix).
	BindFlags(cmd.Flags()).
	Parse()
```

**Review by jribbink — APPROVED** [review]
