### PR TITLE
Fix Config Syntax Error Handling

### LINKED ISSUE #377: Misleading Error Message On Deployment Error
### Issue To Be Solved

I was trying to deploy a contract to testnet using `flow project deploy --network=testnet`. However, I accidentally omitted the "testnet" field in my JSON structure.

I.e. the deployments section of my `flow.json` looked like:

```json
"deployments": {
    "example-account": ["ExampleContract"]
}
```
instead of:

```json
"deployments": {
    "testnet": {
        "example-account": ["ExampleContract"]
    }
}
```

However, when I ran `flow project deploy --network=testnet` I received the error:

However, I did have a `flow.json` in the root of my project, and so of course running `flow init` fails.

### (Optional): Suggest A Solution

This was totally my fault, the JSON that I had in my `flow.json`, while valid JSON structurally, did not contain all of the requirements that Flow CLI required. However, I think that the error message here is lacking a bit as this took a while for me to find what was going on.

I would suggest a more specific error message if Flow CLI parses the JSON for a certain attribute and does not find it, that should likely be reported, instead of reporting that the entire config file is missing.

### PR DESCRIPTION
**Pull request by sideninja**
Closes #377 

## Description
This PR fixes loader error handling for wrong config syntax. The error was wrongly passed.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: pkg/flowkit/config/json/config.go [hunk 1]
```diff
@@ -129,9 +130,8 @@ func (p *Parser) Deserialize(raw []byte) (*config.Config, error) {
 
 	var jsonConf jsonConfig
 	err := json.Unmarshal(raw, &jsonConf)
-
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("configuration syntax error: %v", err)
```
Comment (janezpodhostnik) [inline pkg/flowkit/config/json/config.go:134]: `%w` is probably preferable to `%v` here  
```suggestion
		return nil, fmt.Errorf("configuration syntax error: %w", err)
```

File: pkg/flowkit/config/loader.go [hunk 2]
```diff
@@ -130,12 +130,15 @@ func (l *Loader) Load(paths []string) (*Config, error) {
 	// special case for default configs
 	// try to load local config and only if not found try to load global config
 	if IsDefaultPath(paths) {
-		conf, err := l.LoadConfig(DefaultPath)
-		if err == nil {
+		conf, err := l.loadConfig(DefaultPath)
+		if err == nil { // if we could load it then process it
 			return l.postprocess(conf)
 		}
+		if err != ErrDoesNotExist {
```
Comment (janezpodhostnik) [inline pkg/flowkit/config/loader.go:137]: Consider replacing with
```suggestion
		if errors.Is(err, ErrDoesNotExist) {
```

Comment (sideninja) [reply pkg/flowkit/config/loader.go:137]: Great catch, thank you (not equal tho)

**Review by janezpodhostnik — APPROVED** [review]
